package HealthCentreMemberSystem;
/*
 * HCMember.java
 * Represents a specific Health Centre Member.
 * Encapsulates all personal details (such as name, age, weight)and clinical data (blood pressure, consultation status)
 */
public class HCMember {

    // =========================================================================
    // Validation Constants (The Rules of the System)
    // =========================================================================
    
    /** Minimum age for a member */
    private static final int MIN_AGE = 18;               
    /** Maximum  age for a member */
    private static final int MAX_AGE = 100;              
    
    /** Minimum weight in kg */
    private static final double MIN_WEIGHT = 20.0;       
    /** Maximum weight in kg */
    private static final double MAX_WEIGHT = 150.0;      
    
    /** Minimum valid systolic blood pressure */
    private static final int MIN_SYSTOLIC = 40;          
    /** Maximum valid systolic blood pressure  */
    private static final int MAX_SYSTOLIC = 180;         
    
    /** Minimum valid diastolic blood pressure */
    private static final int MIN_DIASTOLIC = 40;         
    /** Maximum valid diastolic blood pressure */
    private static final int MAX_DIASTOLIC = 120;        
    
    /** Minimum character length for names */
    private static final int MIN_NAME_LENGTH = 2;        
    /** Minimum character length for addresses */
    private static final int MIN_ADDRESS_LENGTH = 5;     
    /** Maximum character length for addresses */
    private static final int MAX_ADDRESS_LENGTH = 100;    
    
    // =========================================================================
    // Instance Variables (Member Data)
    // =========================================================================
    
    private String hcNumber;       // Unique ID
    private String forename;       
    private String surname;        
    private char gender;           
    private String address;        
    private boolean fConsultation; // True if free consultation completed
    private double weight;         
    private int age;               
    private String bloodPressure;  // e.g., "High", "Normal", "Low"
    private int visitTally;        // Counter for visits

    /**
     * Parameterised Constructor.
     * Initialises a new member with specific details.
     * * @param hcNumber  The unique Health Centre ID (generated by the Manager).
     * @param forename  The member's first name.
     * @param surname   The member's last name.
     * @param gender    The member's gender ('M' or 'F').
     * @param age       The member's age in years.
     * @param weight    The member's weight in kg.
     * @param address   The member's home address.
     */
    public HCMember(String hcNumber, String forename, String surname, char gender, int age, double weight, String address) {
        this.hcNumber = hcNumber;
        this.forename = forename;
        this.surname = surname;
        this.gender = gender;
        this.age = age;
        this.weight = weight;
        this.address = address;
        
        // Set defaults for new members
        this.fConsultation = false;
        this.bloodPressure = "Normal"; 
        this.visitTally = 0;
    }

    // =========================================================================
    // Core Logic Methods
    // =========================================================================

    /**
     * Records a visit to the Health Centre.
     * Increments the visit tally and prints a confirmation to the console.
     */
    public void visitedCentre() {
        this.visitTally++;
        System.out.println("Visit recorded. Total visits: " + this.visitTally);
    }

    /**
     * Calculates the blood pressure category 
     * High:Systolic > 140 OR Diastolic > 90
     * Low: Systolic < 90 OR Diastolic < 60
     * Normal:Any other valid reading
     * @return The string category ("High", "Low", "Normal") or "Invalid reading".
     */
    public String calcBloodPressure(int systolic, int diastolic) {
        // Validate inputs 
        if (!isValidSystolic(systolic) || !isValidDiastolic(diastolic)) {
            return "Invalid reading";
        }

        // Determine category
        if (systolic > 140 || diastolic > 90) {
            this.bloodPressure = "High";
        } else if (systolic < 90 || diastolic < 60) {
            this.bloodPressure = "Low";
        } else {
            this.bloodPressure = "Normal";
        }
        return this.bloodPressure;
    }

    /**
     * Returns a formatted string 
     * Uses string for column alignment.
     * @return String containing member details.
     */
    public String memberDetails() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("%-10s %-15s %-15s %-5s %-5d %-10s\n", 
            hcNumber, forename, surname, gender, age, bloodPressure));
        return sb.toString();
    }

    // =========================================================================
    // Static Validation Logic
    // =========================================================================

    /**
     * Checks if an age is within range.
     */
    public static boolean isValidAge(int age) {
        return age >= MIN_AGE && age <= MAX_AGE;
    }

    /**
     * Checks if a weight is within range.
     */
    public static boolean isValidWeight(double weight) {
        return weight >= MIN_WEIGHT && weight <= MAX_WEIGHT;
    }
    
    /**
     * Checks if a name is valid.
     */
    public static boolean isValidName(String name) {
        return name != null && name.trim().length() >= MIN_NAME_LENGTH;
    }

    /**
     * Checks if an address is valid .
     */
    public static boolean isValidAddress(String address) {
        if (address == null) return false;
        String trimmed = address.trim();
        return trimmed.length() >= MIN_ADDRESS_LENGTH && trimmed.length() <= MAX_ADDRESS_LENGTH;
    }

    public static boolean isValidSystolic(int systolic) {
        return systolic >= MIN_SYSTOLIC && systolic <= MAX_SYSTOLIC;
    }

    public static boolean isValidDiastolic(int diastolic) {
        return diastolic >= MIN_DIASTOLIC && diastolic <= MAX_DIASTOLIC;
    }

    // =========================================================================
    // Setters 
    // =========================================================================

    public boolean setAddress(String address) {
        if (isValidAddress(address)) {
            this.address = address.trim();
            return true;
        }
        return false;
    }

    public boolean setAge(int age) {
        if (isValidAge(age)) {
            this.age = age;
            return true;
        }
        return false;
    }

    public boolean setWeight(double weight) {
        if (isValidWeight(weight)) {
            this.weight = weight;
            return true;
        }
        return false;
    }
    
    public void setFConsultation(boolean status) {
        this.fConsultation = status;
    }

    // =========================================================================
    // Getters
    // =========================================================================
    
    public String getHCNumber() { return hcNumber; }
    public String getForename() { return forename; }
    public String getSurname() { return surname; }
    public char getGender() { return gender; }
    public double getWeight() { return weight; }
    public int getAge() { return age; }
    public String getBloodPressure() { return bloodPressure; }
    public boolean isFConsultation() { return fConsultation; }
    public int getVisitTally() { return visitTally; }
    public String getAddress() { return address; }

    // =========================================================================
    // Static Accessors 
    // =========================================================================
    
    public static int getMinAge() { return MIN_AGE; }
    public static int getMaxAge() { return MAX_AGE; }
    public static double getMinWeight() { return MIN_WEIGHT; }
    public static double getMaxWeight() { return MAX_WEIGHT; }
    public static int getMinSystolic() { return MIN_SYSTOLIC; }
    public static int getMaxSystolic() { return MAX_SYSTOLIC; }
    public static int getMinDiastolic() { return MIN_DIASTOLIC; }
    public static int getMaxDiastolic() { return MAX_DIASTOLIC; }
    public static int getMinNameLength() { return MIN_NAME_LENGTH; }
    public static int getMinAddressLength() { return MIN_ADDRESS_LENGTH; }
    public static int getMaxAddressLength() { return MAX_ADDRESS_LENGTH; }

    // =========================================================================
    // Validation Messages
    // =========================================================================
    
    public static String getWeightValidationMessage() {
        return "Weight must be between " + MIN_WEIGHT + " and " + MAX_WEIGHT + "kg.";
    }
    public static String getSystolicValidationMessage() {
        return "Systolic pressure must be between " + MIN_SYSTOLIC + " and " + MAX_SYSTOLIC + ".";
    }
    public static String getDiastolicValidationMessage() {
        return "Diastolic pressure must be between " + MIN_DIASTOLIC + " and " + MAX_DIASTOLIC + ".";
    }
    public static String getNameValidationMessage(String field) {
        return field + " must be at least " + MIN_NAME_LENGTH + " characters.";
    }
    public static String getAddressValidationMessage() {
        return "Address must be between " + MIN_ADDRESS_LENGTH + " and " + MAX_ADDRESS_LENGTH + " characters.";
    }
}